

services:
  db:
    image: postgres:15-alpine
    container_name: qlbds_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: bds_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME:-postgres} -d bds_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    # Kéo Image trực tiếp từ Docker Hub về thay vì tự build ở máy nội bộ
    image: ${DOCKER_USERNAME:-hoangbmt023}/qlbds-api:latest
    container_name: qlbds_app
    restart: always
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=production
      - DB_URL=jdbc:postgresql://db:5432/bds_db 
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME}
      - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
      - CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env.production

volumes:
  postgres_data:
